customhost = "database-2.cyltbqip9evc.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "abcd1234"
customdb = "itps"
custombucket = "ongjingrou-bucket"
customregion = "US East (N. Virginia) us-east-1"